<a href="https://colab.research.google.com/github/GMISSAGLIA/GM_PyLab/blob/Main/Yahoo_Finance_Data_Download_Parte_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Yahoo Finance  e Python : parte 1

In questo Notebook illustrerò le funzioni messe a disposizione dalla principale libreria python che fornisce accesso ai dati di Yahoo Finance.

Lavorerò con un singolo 'ticker' rimandando alla parte 2 l'illustrazione dell'analisi relativa a più 'tickers' in cui mostrerò come effettuare il download di dati più complessi e articolati(dati storici di più azioni, FX, tassi, indici, ETF..)

Principali riferimenti:

Per primo il sito del nostro data provider cioè  Yahoo dove potete rendervi conto di quali dati sono disponibilie quindi il link alla libreria Python

  1.    [yahoo finance](https://finance.yahoo.com/world-indices)
  2.    [Yahoo Finance Python Library: yfinance -](https://pypi.org/project/yfinance/)

Il package yfinance è:
- user-friendly e versatile anche grazie all'integrazione con Pandas;
- supportata da un'ampia documentazione e dalla Community degli utenti e sviluppatori
- Attivamente mantenuta, con aggiornamenti e correzioni di bug.

D'altro canto potrebbero registrarsi a volte problemi di accuratezza dei dati come segnalato da alcuni utenti in relazione ad occasionali discrepanze o dati mancanti rispetto ai download diretti dal sito web di Yahoo Finance.

Quindi la libreria, seppure non possa considerarsi una scelta adatta per usi professionali, è semplice da interpretare e facile da utilizzare e dando accesso ad una buona quantità e varietà di dati e può essere sicuramente usata per sviluppare modelli e algoritmi

Se si si hanno in mente obiettivi più "seri", cioè si vogliono mettere in produzione algoritmi di supporto al trading o supportare decisioni di investimento importanti e si ha a disposizione una postazione Bloomberg meglio utilizzare Bquant, ma questa è un'altra storia....


---


Il presente notebook puo essere eseguito in [Google Colab](https://colab.research.google.com/) o in locale installando la librerie [yfinance](https://pypi.org/project/yfinance/)

In [ ]:
!pip install yfinance

In [2]:
#import necessary library
import pandas as pd
import numpy as np
import datetime
import yfinance as yf

In [42]:
# Set display options for pandas dataframes
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.colheader_justify', 'center')
pd.set_option('display.precision', 3)
pd.options.display.float_format = '{:,.2f}'.format

In [43]:
"""
Scegliamo come esempio il ticker del Monte dei Paschi di Siena
Download delle informazioni principali
i dati sono restituiti in una variabile di tipo Dictionary
"""
TickerName = "BMPS.MI"
Stock = yf.Ticker(TickerName)
StockInfo = Stock.info

In [44]:
type(Stock)

yfinance.ticker.Ticker

In [45]:
Stock.info.keys()

dict_keys(['address1', 'city', 'state', 'zip', 'country', 'phone', 'website', 'industry', 'industryKey', 'industryDisp', 'sector', 'sectorKey', 'sectorDisp', 'longBusinessSummary', 'fullTimeEmployees', 'companyOfficers', 'auditRisk', 'boardRisk', 'compensationRisk', 'shareHolderRightsRisk', 'overallRisk', 'governanceEpochDate', 'compensationAsOfEpochDate', 'maxAge', 'priceHint', 'previousClose', 'open', 'dayLow', 'dayHigh', 'regularMarketPreviousClose', 'regularMarketOpen', 'regularMarketDayLow', 'regularMarketDayHigh', 'dividendRate', 'dividendYield', 'exDividendDate', 'payoutRatio', 'fiveYearAvgDividendYield', 'beta', 'trailingPE', 'forwardPE', 'volume', 'regularMarketVolume', 'averageVolume', 'averageVolume10days', 'averageDailyVolume10Day', 'bid', 'ask', 'marketCap', 'fiftyTwoWeekLow', 'fiftyTwoWeekHigh', 'priceToSalesTrailing12Months', 'fiftyDayAverage', 'twoHundredDayAverage', 'trailingAnnualDividendRate', 'trailingAnnualDividendYield', 'currency', 'enterpriseValue', 'profitMargins', 'floatShares', 'sharesOutstanding', 'heldPercentInsiders', 'heldPercentInstitutions', 'impliedSharesOutstanding', 'bookValue', 'priceToBook', 'lastFiscalYearEnd', 'nextFiscalYearEnd', 'mostRecentQuarter', 'earningsQuarterlyGrowth', 'netIncomeToCommon', 'trailingEps', 'forwardEps', 'pegRatio', 'lastSplitFactor', 'lastSplitDate', 'enterpriseToRevenue', '52WeekChange', 'SandP52WeekChange', 'lastDividendValue', 'lastDividendDate', 'exchange', 'quoteType', 'symbol', 'underlyingSymbol', 'shortName', 'longName', 'firstTradeDateEpochUtc', 'timeZoneFullName', 'timeZoneShortName', 'uuid', 'messageBoardId', 'gmtOffSetMilliseconds', 'currentPrice', 'targetHighPrice', 'targetLowPrice', 'targetMeanPrice', 'targetMedianPrice', 'recommendationMean', 'recommendationKey', 'numberOfAnalystOpinions', 'totalCash', 'totalCashPerShare', 'totalDebt', 'totalRevenue', 'revenuePerShare', 'returnOnAssets', 'returnOnEquity', 'earningsGrowth', 'revenueGrowth', 'operatingMargins', 'financialCurrency', 'trailingPegRatio'])

In [46]:
StockInfo

{'address1': 'Piazza Salimbeni 3',
 'city': 'Siena',
 'state': 'SI',
 'zip': '53100',
 'country': 'Italy',
 'phone': '39 0577 29 41 11',
 'website': 'https://www.gruppomps.it',
 'industry': 'Banks - Regional',
 'industryKey': 'banks-regional',
 'industryDisp': 'Banks - Regional',
 'sector': 'Financial Services',
 'sectorKey': 'financial-services',
 'sectorDisp': 'Financial Services',
 'longBusinessSummary': 'Banca Monte dei Paschi di Siena S.p.A., together with its subsidiaries, engages in the provision of retail and commercial banking services in Italy. The company operates through Retail Banking, Wealth Management, Corporate Banking, Large Corporate and Investment Banking, and Corporate Centre segments. It offers funding and lending services, insurance products, financial advisory and planning, and electronic payment services; financial and non-financial services; wealth management and financial planning services; consultancy services, such as tax planning, real estate, art, and legal advisory; fiduciary and trust services; and digital banking services. The company also provides leasing and factoring services for businesses, artisans, and professionals, as well as offers mid- and long-term lending, mortgage and personal lending, corporate finance, investment banking, capital markets, and structured finance services. In addition, it provides investment banking products and services, deposit account, cards, and advanced payment systems; foreign banking services; and custody and deposit services for dairy products on behalf of third parties. Further, the company develops and manages IT and telecommunication systems. Banca Monte dei Paschi di Siena S.p.A. was founded in 1472 and is headquartered in Siena, Italy.',
 'fullTimeEmployees': 16632,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Luigi  Lovaglio',
   'age': 68,
   'title': 'CEO, GM & Director',
   'yearBorn': 1955,
   'fiscalYear': 2022,
   'totalPay': 487376,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Andrea  Maffezzoni',
   'title': 'Chief Financial Officer',
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Alessandro  Giacometti',
   'title': 'Chief Operating Officer',
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Giovanni  Damiani',
   'title': 'Chief Information Office',
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Elisabetta  Pozzi',
   'title': 'Head of Investor Relations',
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Renzo Filippo Riccardo Quagliana',
   'title': 'Group General Counsel',
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ettore  Carneade',
   'title': 'Chief Compliance Executive',
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Fiorella  Ferri',
   'title': 'Chief Human Capital Officer',
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Maurizio  Bai',
   'title': 'Deputy Commercial General Manager',
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Fabrizio  Leandri',
   'age': 57,
   'title': 'Chief Lending Officer',
   'yearBorn': 1966,
   'fiscalYear': 2022,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 6,
 'boardRisk': 1,
 'compensationRisk': 4,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1722470400,
 'compensationAsOfEpochDate': 1672444800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 5.148,
 'open': 5.176,
 'dayLow': 5.092,
 'dayHigh': 5.176,
 'regularMarketPreviousClose': 5.148,
 'regularMarketOpen': 5.176,
 'regularMarketDayLow': 5.092,
 'regularMarketDayHigh': 5.176,
 'dividendRate': 0.25,
 'dividendYield': 0.048699997,
 'exDividendDate': 1716163200,
 'payoutRatio': 0.1204,
 'fiveYearAvgDividendYield': 5.05,
 'beta': 1.068,
 'trailingPE': 2.4673078,
 'forwardPE': 5.9674416,
 'volume': 10023041,
 'regularMarketVolume': 10023041,
 'averageVolume': 17869588,
 'averageVolume10days': 21580064,
 'averageDailyVolume10Day': 21580064,
 'bid': 5.114,
 'ask': 5.116,
 'marketCap': 6464729088,
 'fiftyTwoWeekLow': 2.232,
 'fiftyTwoWeekHigh': 5.364,
 'priceToSalesTrailing12Months': 1.833248,
 'fiftyDayAverage': 4.80592,
 'twoHundredDayAverage': 4.02326,
 'trailingAnnualDividendRate': 0.25,
 'trailingAnnualDividendYield': 0.04856255,
 'currency': 'EUR',
 'enterpriseValue': -1339106688,
 'profitMargins': 0.73503,
 'floatShares': 921174247,
 'sharesOutstanding': 1259689984,
 'heldPercentInsiders': 0.26733,
 'heldPercentInstitutions': 0.22635001,
 'impliedSharesOutstanding': 1265069952,
 'bookValue': 8.586,
 'priceToBook': 0.59771717,
 'lastFiscalYearEnd': 1703980800,
 'nextFiscalYearEnd': 1735603200,
 'mostRecentQuarter': 1719705600,
 'earningsQuarterlyGrowth': 1.156,
 'netIncomeToCommon': 2591981056,
 'trailingEps': 2.08,
 'forwardEps': 0.86,
 'pegRatio': -1.71,
 'lastSplitFactor': '1:100',
 'lastSplitDate': 1664150400,
 'enterpriseToRevenue': -0.38,
 '52WeekChange': 0.89372694,
 'SandP52WeekChange': 0.24822903,
 'lastDividendValue': 0.25,
 'lastDividendDate': 1716163200,
 'exchange': 'MIL',
 'quoteType': 'EQUITY',
 'symbol': 'BMPS.MI',
 'underlyingSymbol': 'BMPS.MI',
 'shortName': 'BANCA MONTE PASCHI SIENA',
 'longName': 'Banca Monte dei Paschi di Siena S.p.A.',
 'firstTradeDateEpochUtc': 930294000,
 'timeZoneFullName': 'Europe/Rome',
 'timeZoneShortName': 'CEST',
 'uuid': '192c6fc0-fc94-39a2-8693-2c29dfc3d6c6',
 'messageBoardId': 'finmb_691202',
 'gmtOffSetMilliseconds': 7200000,
 'currentPrice': 5.132,
 'targetHighPrice': 6.6,
 'targetLowPrice': 5.3,
 'targetMeanPrice': 6.1,
 'targetMedianPrice': 6.2,
 'recommendationMean': 2.4,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 8,
 'totalCash': 20600999936,
 'totalCashPerShare': 16.386,
 'totalDebt': 12809199616,
 'totalRevenue': 3526380032,
 'revenuePerShare': 2.803,
 'returnOnAssets': 0.02078,
 'returnOnEquity': 0.26864,
 'earningsGrowth': 1.16,
 'revenueGrowth': 0.008,
 'operatingMargins': 0.50493,
 'financialCurrency': 'EUR',
 'trailingPegRatio': None}

In [47]:
"""
Download dei dati storici usando data inizio e fine
frequenza giornaliera, data inizio e fine possono essere fornite in input anche nel formato di stringhe
"""
tipoinput = 0

if tipoinput == 0 :
  start = datetime.datetime(2022,2,1)
  end = datetime.datetime(2024,6,30)
else:
  start = '2022-2-1'
  end = '2022-11-11'

StockHist = Stock.history(start= start, end= end)

type(StockHist)
StockHist['Volume'] = StockHist.apply(lambda x: "{:,.0f}".format(x['Volume']), axis=1)
StockHist.head()

                           Open  High   Low  Close  Volume   Dividends  Stock Splits
Date
2022-02-01 00:00:00+01:00 18.24 18.50 17.99 18.29   148,931    0.00         0.00
2022-02-02 00:00:00+01:00 18.44 19.02 18.30 18.66   378,368    0.00         0.00
2022-02-03 00:00:00+01:00 19.00 19.00 18.57 18.83   232,939    0.00         0.00
2022-02-04 00:00:00+01:00 18.98 19.06 18.26 18.36   264,963    0.00         0.00
2022-02-07 00:00:00+01:00 18.36 18.72 18.26 18.46   194,072    0.00         0.00

In [8]:
"""
 Download dei dati storici usando period (definisce la lunghezza dell'intervallo di tempo) e frequenza giornaliera
"""
StockHist = Stock.history(period='max')
type(StockHist)
StockHist['Volume'] = StockHist.apply(lambda x: "{:,.0f}".format(x['Volume']), axis=1)
StockHist.head()

                               Open           High            Low           Close     Volume  Dividends  Stock Splits
Date
1999-06-25 00:00:00+02:00 263,174,716.80 265,651,652.77 254,505,419.30 262,555,472.00  1,982    0.00         0.00
1999-06-28 00:00:00+02:00 266,270,872.87 269,367,031.74 262,555,447.65 266,890,096.00    812    0.00         0.00
1999-06-29 00:00:00+02:00 268,747,845.77 268,747,845.77 260,697,792.70 263,793,952.00    455    0.00         0.00
1999-06-30 00:00:00+02:00 264,413,199.12 266,270,912.00 261,317,018.19 266,270,912.00    232    0.00         0.00
1999-07-01 00:00:00+02:00 267,509,360.16 278,036,348.62 265,032,402.63 272,463,232.00    393    0.00         0.00

# Analisi delle principali informazioni ed eventi

In [10]:
StockActions =Stock.actions
StockActions.head()

                            Dividends   Stock Splits
Date
2000-05-22 00:00:00+02:00 7,164,389.50      0.00
2001-05-21 00:00:00+02:00 8,955,487.00      0.00
2002-05-20 00:00:00+02:00     4,625.51      0.00
2003-05-19 00:00:00+02:00     3,725.48      0.00
2004-05-24 00:00:00+02:00     2,444.85      0.00

In [11]:
StockDividends= Stock.dividends
StockDividends.head()

Date
2000-05-22 00:00:00+02:00   7,164,389.50
2001-05-21 00:00:00+02:00   8,955,487.00
2002-05-20 00:00:00+02:00       4,625.51
2003-05-19 00:00:00+02:00       3,725.48
2004-05-24 00:00:00+02:00       2,444.85
Name: Dividends, dtype: float64

# Dati di Bilancio e Finanziari

In [ ]:
#Dati di Bilancio
Stock.balance_sheet

                                                       2023-12-31         2022-12-31         2021-12-31         2020-12-31         2019-12-31
Treasury Shares Number                                            NaN                NaN      36,280,748.00       1,741,168.00      1,741,168.00
Ordinary Shares Number                               1,259,689,706.00   1,259,689,706.00      48,106,975.00      46,365,807.00               NaN
Share Issued                                         1,259,689,706.00   1,259,689,706.00      48,106,975.00      48,106,975.00               NaN
Net Debt                                                          NaN                NaN                NaN                NaN 10,511,167,000.00
Total Debt                                          12,941,704,000.00  10,303,201,000.00  12,737,640,000.00  16,536,002,000.00               NaN
Tangible Book Value                                  9,800,234,000.00   7,697,345,000.00   5,987,423,000.00   5,587,659,000.00               NaN
Invested Capital                                    22,729,006,000.00  17,952,002,000.00  18,684,125,000.00  22,084,881,000.00               NaN
Net Tangible Assets                                  9,800,234,000.00   7,697,345,000.00   5,987,423,000.00   5,587,659,000.00               NaN
Common Stock Equity                                  9,978,458,000.00   7,859,994,000.00   6,172,652,000.00   5,771,604,000.00               NaN
Total Capitalization                                22,729,006,000.00  17,952,002,000.00  18,684,125,000.00  22,084,881,000.00               NaN
Total Equity Gross Minority Interest                 9,979,109,000.00   7,860,930,000.00   6,173,998,000.00   5,772,914,000.00               NaN
Minority Interest                                          651,000.00         936,000.00       1,346,000.00       1,310,000.00               NaN
Stockholders Equity                                  9,978,458,000.00   7,859,994,000.00   6,172,652,000.00   5,771,604,000.00               NaN
Fixed Assets Revaluation Reserve                                  NaN                NaN                NaN                NaN     66,394,000.00
Treasury Stock                                                    NaN                NaN               0.00     313,710,000.00    313,710,000.00
Retained Earnings                                    2,051,781,000.00    -178,361,000.00     309,507,000.00  -1,686,507,000.00               NaN
Capital Stock                                        7,453,451,000.00   7,453,451,000.00   9,195,012,000.00   9,195,012,000.00               NaN
Common Stock                                         7,453,451,000.00   7,453,451,000.00   9,195,012,000.00   9,195,012,000.00               NaN
Total Liabilities Net Minority Interest            112,634,582,000.00 112,374,374,000.00 131,694,564,000.00 144,572,122,000.00               NaN
Derivative Product Liabilities                       1,345,635,000.00   1,645,538,000.00   2,701,965,000.00   3,298,998,000.00               NaN
Long Term Debt And Capital Lease Obligation         12,941,704,000.00  10,303,201,000.00  12,737,640,000.00  16,536,002,000.00               NaN
Payables                                             1,157,305,000.00   1,333,541,000.00     566,996,000.00     707,113,000.00               NaN
Other Payable                                          740,324,000.00     967,711,000.00     154,164,000.00     284,580,000.00               NaN
Total Tax Payable                                      221,357,000.00     167,977,000.00     135,340,000.00     122,254,000.00               NaN
Accounts Payable                                       195,624,000.00     197,853,000.00     277,492,000.00     300,279,000.00               NaN
Total Assets                                       122,613,691,000.00 120,235,304,000.00 137,868,562,000.00 150,345,036,000.00               NaN
Investments And Advances                            20,218,313,000.00  21,649,133,000.00  26,248,553,000.00  26,781,336,000.00               NaN
Investmentin Financial Assets                       19,491,622,000.00  20,898,455,000.00  25,153,141,000.00  25,673,873,000.00               NaN
Available For Sale Securities                       13,220,401,000.00  14,115,944,000.00  15,013,577,000.00  16,057,785,000.00               NaN
Financial Assets Designatedas Fair Value Throug...     245,475,000.00     314,759,000.00     322,582,000.00     317,885,000.00               NaN
Trading Securities                                   3,810,574,000.00   3,962,917,000.00   6,790,936,000.00   5,247,146,000.00               NaN
Long Term Equity Investment                            726,691,000.00     750,678,000.00   1,095,412,000.00   1,107,463,000.00               NaN
Investment Properties                                  285,247,000.00     303,689,000.00     254,240,000.00     247,464,000.00               NaN
Goodwill And Other Intangible Assets                   178,224,000.00     162,649,000.00     185,229,000.00     183,945,000.00               NaN
Other Intangible Assets                                170,324,000.00     154,749,000.00     177,329,000.00     176,045,000.00               NaN
Goodwill                                                 7,900,000.00       7,900,000.00       7,900,000.00       7,900,000.00               NaN
Net PPE                                              1,943,452,000.00   2,072,237,000.00   2,235,891,000.00   2,088,348,000.00               NaN
Gross PPE                                            1,943,452,000.00   2,072,237,000.00   2,235,891,000.00   2,088,348,000.00               NaN
Other Properties                                        95,545,000.00     118,984,000.00     145,591,000.00     194,496,000.00               NaN
Machinery Furniture Equipment                          132,490,000.00     136,776,000.00     142,470,000.00     145,418,000.00               NaN
Buildings And Improvements                             831,869,000.00     852,635,000.00     884,566,000.00   1,114,060,000.00               NaN
Land And Improvements                                  883,548,000.00     963,842,000.00   1,063,264,000.00     634,374,000.00               NaN
Prepaid Assets                                         523,278,000.00     512,071,000.00     516,785,000.00     506,993,000.00               NaN
Receivables                                              5,811,000.00      33,564,000.00      10,734,000.00      20,132,000.00               NaN
Taxes Receivable                                     2,197,551,000.00   1,718,293,000.00   1,147,190,000.00   1,056,754,000.00               NaN
Cash And Cash Equivalents                           15,579,350,000.00  13,598,205,000.00  23,046,584,000.00  31,390,260,000.00               NaN
Cash Equivalents                                                  NaN                NaN                NaN      78,883,000.00     57,406,000.00
Cash Financial                                         708,220,000.00     695,933,000.00     723,876,000.00     751,985,000.00               NaN
Cash Cash Equivalents And Federal Funds Sold        22,839,923,000.00  17,687,703,000.00  28,985,791,000.00  40,902,934,000.00               NaN

In [13]:
Stock.quarterly_balance_sheet.head()

                           2024-06-30        2024-03-31        2023-12-31        2023-09-30        2023-06-30    2023-03-31 2022-12-31
Ordinary Shares Number  1,259,689,706.00  1,259,689,706.00  1,259,689,706.00  1,259,689,706.00  1,259,689,706.00     NaN        NaN
Share Issued            1,259,689,706.00  1,259,689,706.00  1,259,689,706.00  1,259,689,706.00  1,259,689,706.00     NaN        NaN
Total Debt             10,341,500,000.00  9,514,000,000.00 12,941,704,000.00  9,919,700,000.00  9,551,900,000.00     NaN        NaN
Tangible Book Value    10,787,100,000.00 10,299,200,000.00  9,800,234,000.00  8,799,200,000.00  8,362,400,000.00     NaN        NaN
Invested Capital       21,136,500,000.00 19,821,100,000.00 22,729,006,000.00 18,726,800,000.00 18,051,400,000.00     NaN        NaN

In [14]:
#Dati Finanziari
Stock.financials

                                                      2023-12-31       2022-12-31       2021-12-31        2020-12-31      2019-12-31
Tax Effect Of Unusual Items                          -26,592,240.00   -23,335,200.00   -22,336,800.00     -7,392,240.00            NaN
Tax Rate For Calcs                                             0.24             0.24             0.24              0.24            NaN
Total Unusual Items                                 -110,801,000.00   -97,230,000.00   -93,070,000.00    -30,801,000.00            NaN
Total Unusual Items Excluding Goodwill              -110,801,000.00   -97,230,000.00   -93,070,000.00    -30,801,000.00            NaN
Net Income From Continuing Operation Net Minori... 2,051,781,000.00  -178,361,000.00   309,507,000.00 -1,686,507,000.00            NaN
Reconciled Depreciation                              181,084,000.00   193,466,000.00   208,567,000.00    243,143,000.00            NaN
Net Interest Income                                2,291,928,000.00 1,535,236,000.00 1,217,048,000.00  1,271,446,000.00            NaN
Interest Expense                                   2,072,241,000.00   614,485,000.00   680,342,000.00    703,663,000.00            NaN
Interest Income                                    4,364,169,000.00 2,149,721,000.00 1,897,390,000.00  1,975,109,000.00            NaN
Normalized Income                                  2,135,989,760.00  -104,466,200.00   380,240,200.00 -1,663,098,240.00            NaN
Net Income From Continuing And Discontinued Ope... 2,051,781,000.00  -178,361,000.00   309,507,000.00 -1,686,507,000.00            NaN
Diluted Average Shares                             1,259,689,706.00   209,865,416.00    47,322,061.00     52,421,063.00            NaN
Basic Average Shares                               1,259,689,706.00   209,865,416.00    47,322,061.00     52,421,063.00            NaN
Diluted EPS                                                    1.63            -0.85             6.54            -32.17            NaN
Basic EPS                                                      1.63            -0.85             6.54            -32.17            NaN
Diluted NI Availto Com Stockholders                2,051,781,000.00  -178,361,000.00   309,507,000.00 -1,686,507,000.00            NaN
Net Income Common Stockholders                     2,051,781,000.00  -178,361,000.00   309,507,000.00 -1,686,507,000.00            NaN
Otherunder Preferred Stock Dividend                             NaN     2,700,000.00     3,600,000.00      4,300,000.00            NaN
Net Income                                         2,051,781,000.00  -178,361,000.00   309,507,000.00 -1,686,507,000.00            NaN
Minority Interests                                       156,000.00       148,000.00       176,000.00        129,000.00            NaN
Net Income Including Noncontrolling Interests      2,051,625,000.00  -178,509,000.00   309,331,000.00 -1,686,636,000.00            NaN
Net Income Discontinuous Operations                             NaN              NaN              NaN              0.00 -18,060,000.00
Net Income Continuous Operations                   2,051,625,000.00  -178,509,000.00   309,331,000.00 -1,686,636,000.00            NaN
Tax Provision                                       -345,117,000.00  -426,620,000.00   -51,167,000.00    339,407,000.00            NaN
Pretax Income                                      1,706,508,000.00  -605,129,000.00   258,164,000.00 -1,347,229,000.00            NaN
Special Income Charges                              -111,228,000.00   -97,452,000.00  -110,771,000.00    -85,146,000.00            NaN
Other Special Charges                                 53,144,000.00    31,111,000.00    44,134,000.00     19,113,000.00            NaN
Write Off                                                       NaN              NaN              NaN      1,262,000.00      -1,000.00
Impairment Of Capital Assets                             718,000.00       705,000.00     3,277,000.00     15,072,000.00            NaN
Restructuring And Mergern Acquisition                 57,366,000.00    66,341,000.00    66,637,000.00     66,033,000.00            NaN
Gain On Sale Of Security                               8,844,000.00    41,946,000.00   -11,767,000.00     -2,065,000.00            NaN
Operating Expense                                  1,805,689,000.00 3,459,164,000.00 2,729,555,000.00  3,801,311,000.00            NaN
Other Operating Expenses                            -201,889,000.00   244,992,000.00   402,368,000.00  1,288,355,000.00            NaN
Depreciation And Amortization In Income Statement    181,084,000.00   193,466,000.00   208,567,000.00    243,143,000.00            NaN
Amortization                                          66,587,000.00    68,586,000.00    67,451,000.00     75,429,000.00            NaN
Depreciation Income Statement                        114,497,000.00   124,880,000.00   141,116,000.00    167,714,000.00            NaN
Selling General And Administration                   523,907,000.00   590,118,000.00   586,274,000.00    659,080,000.00            NaN
Selling And Marketing Expense                          6,316,000.00     3,139,000.00     3,459,000.00      5,448,000.00            NaN
General And Administrative Expense                   517,591,000.00   586,979,000.00   582,815,000.00    653,632,000.00            NaN
Insurance And Claims                                            NaN    19,857,000.00    41,329,000.00     47,453,000.00  49,216,000.00
Rent And Landing Fees                                163,215,000.00   170,009,000.00   162,712,000.00    162,515,000.00            NaN
Total Revenue                                      3,982,436,000.00 3,287,501,000.00 3,183,800,000.00  3,183,990,000.00            NaN
Operating Revenue                                  3,982,436,000.00 3,287,501,000.00 3,183,800,000.00  3,183,990,000.00            NaN

In [16]:
Stock.quarterly_financials.head()

                                                     2024-06-30     2024-03-31      2023-12-31      2023-09-30     2023-06-30   2023-03-31 2022-12-31
Tax Effect Of Unusual Items                        -12,720,000.00     -80,160.62    -9,024,000.00  -3,144,000.00    -573,569.62     NaN        NaN
Tax Rate For Calcs                                           0.24           0.01             0.24           0.24           0.03     NaN        NaN
Total Unusual Items                                -53,000,000.00  -7,700,000.00   -37,600,000.00 -13,100,000.00 -19,200,000.00     NaN        NaN
Total Unusual Items Excluding Goodwill             -53,000,000.00  -7,700,000.00   -37,600,000.00 -13,100,000.00 -19,200,000.00     NaN        NaN
Net Income From Continuing Operation Net Minori... 826,500,000.00 332,700,000.00 1,123,200,000.00 309,600,000.00 383,300,000.00     NaN        NaN

In [17]:
Stock.cashflow

                                                2023-12-31        2022-12-31        2021-12-31        2020-12-31      2019-12-31
Free Cash Flow                               1,662,907,000.00  8,315,752,000.00   -662,857,000.00 -1,227,560,000.00           NaN
Capital Expenditure                           -111,438,000.00    -65,710,000.00   -111,321,000.00   -145,443,000.00           NaN
End Cash Position                           14,317,277,000.00 12,538,578,000.00  1,741,766,000.00  2,319,441,000.00           NaN
Other Cash Adjustment Outside Changein Cash          1,000.00               NaN               NaN               NaN           NaN
Beginning Cash Position                     12,538,578,000.00  1,741,766,000.00  2,319,441,000.00  3,408,419,000.00           NaN
Changes In Cash                              1,778,698,000.00 10,796,812,000.00   -577,675,000.00 -1,088,978,000.00           NaN
Financing Cash Flow                             -2,726,000.00  2,371,263,000.00     42,928,000.00       -331,000.00           NaN
Cash Dividends Paid                                -96,000.00        -86,000.00        -53,000.00       -331,000.00           NaN
Common Stock Dividend Paid                         -96,000.00        -86,000.00        -53,000.00       -331,000.00           NaN
Net Common Stock Issuance                       -2,630,000.00  2,371,349,000.00     42,981,000.00              0.00           NaN
Investing Cash Flow                              7,079,000.00     44,087,000.00    -69,067,000.00     -6,530,000.00           NaN
Dividends Received Cfi                         116,367,000.00    107,267,000.00     30,370,000.00        638,000.00           NaN
Net Business Purchase And Sale                            NaN              0.00      1,021,000.00              0.00 43,508,000.00
Sale Of Business                                          NaN              0.00      1,021,000.00              0.00 43,508,000.00
Net Intangibles Purchase And Sale              -83,033,000.00    -46,468,000.00    -68,943,000.00    -83,291,000.00           NaN
Sale Of Intangibles                                       NaN              0.00      2,633,000.00         99,000.00    217,000.00
Purchase Of Intangibles                        -83,033,000.00    -46,468,000.00    -71,576,000.00    -83,390,000.00           NaN
Net PPE Purchase And Sale                      -26,255,000.00    -16,712,000.00    -31,515,000.00     76,123,000.00           NaN
Sale Of PPE                                      2,150,000.00      2,530,000.00      8,230,000.00    138,176,000.00           NaN
Purchase Of PPE                                -28,405,000.00    -19,242,000.00    -39,745,000.00    -62,053,000.00           NaN
Operating Cash Flow                          1,774,345,000.00  8,381,462,000.00   -551,536,000.00 -1,082,117,000.00           NaN
Change In Working Capital                      -97,294,000.00  8,613,799,000.00 -1,371,602,000.00 -1,602,279,000.00           NaN
Change In Other Current Liabilities            -40,375,000.00 -1,194,571,000.00   -973,590,000.00   -331,126,000.00           NaN
Change In Other Current Assets                -655,591,000.00   -113,263,000.00    745,870,000.00    140,324,000.00           NaN
Other Non Cash Items                           -88,278,000.00    -91,011,000.00   -136,015,000.00   -156,381,000.00           NaN
Provisionand Write Offof Assets                368,513,000.00    748,386,000.00    665,424,000.00  2,183,704,000.00           NaN
Deferred Tax                                  -345,117,000.00   -426,620,000.00    -51,167,000.00    339,407,000.00           NaN
Gain Loss On Investment Securities            -115,104,000.00   -284,583,000.00     32,493,000.00   -159,932,000.00           NaN
Net Income From Continuing Operations        2,051,625,000.00   -178,509,000.00    309,331,000.00 -1,686,636,000.00           NaN

In [18]:
Stock.quarterly_cashflow

Empty DataFrame
Columns: []
Index: []

In [19]:
Stock.get_income_stmt()

                                                      2023-12-31       2022-12-31       2021-12-31        2020-12-31      2019-12-31
TaxEffectOfUnusualItems                              -26,592,240.00   -23,335,200.00   -22,336,800.00     -7,392,240.00            NaN
TaxRateForCalcs                                                0.24             0.24             0.24              0.24            NaN
TotalUnusualItems                                   -110,801,000.00   -97,230,000.00   -93,070,000.00    -30,801,000.00            NaN
TotalUnusualItemsExcludingGoodwill                  -110,801,000.00   -97,230,000.00   -93,070,000.00    -30,801,000.00            NaN
NetIncomeFromContinuingOperationNetMinorityInte... 2,051,781,000.00  -178,361,000.00   309,507,000.00 -1,686,507,000.00            NaN
ReconciledDepreciation                               181,084,000.00   193,466,000.00   208,567,000.00    243,143,000.00            NaN
NetInterestIncome                                  2,291,928,000.00 1,535,236,000.00 1,217,048,000.00  1,271,446,000.00            NaN
InterestExpense                                    2,072,241,000.00   614,485,000.00   680,342,000.00    703,663,000.00            NaN
InterestIncome                                     4,364,169,000.00 2,149,721,000.00 1,897,390,000.00  1,975,109,000.00            NaN
NormalizedIncome                                   2,135,989,760.00  -104,466,200.00   380,240,200.00 -1,663,098,240.00            NaN
NetIncomeFromContinuingAndDiscontinuedOperation    2,051,781,000.00  -178,361,000.00   309,507,000.00 -1,686,507,000.00            NaN
DilutedAverageShares                               1,259,689,706.00   209,865,416.00    47,322,061.00     52,421,063.00            NaN
BasicAverageShares                                 1,259,689,706.00   209,865,416.00    47,322,061.00     52,421,063.00            NaN
DilutedEPS                                                     1.63            -0.85             6.54            -32.17            NaN
BasicEPS                                                       1.63            -0.85             6.54            -32.17            NaN
DilutedNIAvailtoComStockholders                    2,051,781,000.00  -178,361,000.00   309,507,000.00 -1,686,507,000.00            NaN
NetIncomeCommonStockholders                        2,051,781,000.00  -178,361,000.00   309,507,000.00 -1,686,507,000.00            NaN
OtherunderPreferredStockDividend                                NaN     2,700,000.00     3,600,000.00      4,300,000.00            NaN
NetIncome                                          2,051,781,000.00  -178,361,000.00   309,507,000.00 -1,686,507,000.00            NaN
MinorityInterests                                        156,000.00       148,000.00       176,000.00        129,000.00            NaN
NetIncomeIncludingNoncontrollingInterests          2,051,625,000.00  -178,509,000.00   309,331,000.00 -1,686,636,000.00            NaN
NetIncomeDiscontinuousOperations                                NaN              NaN              NaN              0.00 -18,060,000.00
NetIncomeContinuousOperations                      2,051,625,000.00  -178,509,000.00   309,331,000.00 -1,686,636,000.00            NaN
TaxProvision                                        -345,117,000.00  -426,620,000.00   -51,167,000.00    339,407,000.00            NaN
PretaxIncome                                       1,706,508,000.00  -605,129,000.00   258,164,000.00 -1,347,229,000.00            NaN
SpecialIncomeCharges                                -111,228,000.00   -97,452,000.00  -110,771,000.00    -85,146,000.00            NaN
OtherSpecialCharges                                   53,144,000.00    31,111,000.00    44,134,000.00     19,113,000.00            NaN
WriteOff                                                        NaN              NaN              NaN      1,262,000.00      -1,000.00
ImpairmentOfCapitalAssets                                718,000.00       705,000.00     3,277,000.00     15,072,000.00            NaN
RestructuringAndMergernAcquisition                    57,366,000.00    66,341,000.00    66,637,000.00     66,033,000.00            NaN
GainOnSaleOfSecurity                                   8,844,000.00    41,946,000.00   -11,767,000.00     -2,065,000.00            NaN
OperatingExpense                                   1,805,689,000.00 3,459,164,000.00 2,729,555,000.00  3,801,311,000.00            NaN
OtherOperatingExpenses                              -201,889,000.00   244,992,000.00   402,368,000.00  1,288,355,000.00            NaN
DepreciationAndAmortizationInIncomeStatement         181,084,000.00   193,466,000.00   208,567,000.00    243,143,000.00            NaN
Amortization                                          66,587,000.00    68,586,000.00    67,451,000.00     75,429,000.00            NaN
DepreciationIncomeStatement                          114,497,000.00   124,880,000.00   141,116,000.00    167,714,000.00            NaN
SellingGeneralAndAdministration                      523,907,000.00   590,118,000.00   586,274,000.00    659,080,000.00            NaN
SellingAndMarketingExpense                             6,316,000.00     3,139,000.00     3,459,000.00      5,448,000.00            NaN
GeneralAndAdministrativeExpense                      517,591,000.00   586,979,000.00   582,815,000.00    653,632,000.00            NaN
InsuranceAndClaims                                              NaN    19,857,000.00    41,329,000.00     47,453,000.00  49,216,000.00
RentAndLandingFees                                   163,215,000.00   170,009,000.00   162,712,000.00    162,515,000.00            NaN
TotalRevenue                                       3,982,436,000.00 3,287,501,000.00 3,183,800,000.00  3,183,990,000.00            NaN
OperatingRevenue                                   3,982,436,000.00 3,287,501,000.00 3,183,800,000.00  3,183,990,000.00            NaN

In [20]:
Stock.get_income_stmt(freq='quarterly')

                                                      2024-06-30       2024-03-31       2023-12-31       2023-09-30       2023-06-30      2023-03-31    2022-12-31
TaxEffectOfUnusualItems                              -12,720,000.00       -80,160.62    -9,024,000.00    -3,144,000.00      -573,569.62           NaN           NaN
TaxRateForCalcs                                                0.24             0.01             0.24             0.24             0.03           NaN           NaN
TotalUnusualItems                                    -53,000,000.00    -7,700,000.00   -37,600,000.00   -13,100,000.00   -19,200,000.00           NaN           NaN
TotalUnusualItemsExcludingGoodwill                   -53,000,000.00    -7,700,000.00   -37,600,000.00   -13,100,000.00   -19,200,000.00           NaN           NaN
NetIncomeFromContinuingOperationNetMinorityInte...   826,500,000.00   332,700,000.00 1,123,200,000.00   309,600,000.00   383,300,000.00           NaN           NaN
ReconciledDepreciation                                42,000,000.00    42,400,000.00    44,400,000.00    44,800,000.00    43,000,000.00           NaN           NaN
NetInterestIncome                                    585,200,000.00   587,000,000.00   604,200,000.00   605,000,000.00   578,300,000.00           NaN           NaN
InterestIncome                                       585,200,000.00   587,000,000.00   604,200,000.00   605,000,000.00   578,300,000.00           NaN           NaN
NormalizedIncome                                     866,780,000.00   340,319,839.38 1,151,776,000.00   319,556,000.00   401,926,430.38           NaN           NaN
NetIncomeFromContinuingAndDiscontinuedOperation      826,500,000.00   332,700,000.00 1,123,200,000.00   309,600,000.00   383,300,000.00           NaN           NaN
DilutedAverageShares                               1,259,689,706.00 1,260,227,273.00 1,259,689,706.00 1,259,689,706.00 1,259,689,706.00           NaN           NaN
BasicAverageShares                                 1,259,689,706.00 1,260,227,273.00 1,259,689,706.00 1,259,689,706.00 1,259,689,706.00           NaN           NaN
DilutedEPS                                                     0.66             0.26             0.89             0.25             0.30           NaN           NaN
BasicEPS                                                       0.66             0.26             0.89             0.25             0.30           NaN           NaN
DilutedNIAvailtoComStockholders                      826,500,000.00   332,700,000.00 1,123,200,000.00   309,600,000.00   383,300,000.00           NaN           NaN
NetIncomeCommonStockholders                          826,500,000.00   332,700,000.00 1,123,200,000.00   309,600,000.00   383,300,000.00           NaN           NaN
OtherunderPreferredStockDividend                                NaN              NaN              NaN              NaN              NaN           NaN    500,000.00
NetIncome                                            826,500,000.00   332,700,000.00 1,123,200,000.00   309,600,000.00   383,300,000.00           NaN           NaN
MinorityInterests                                        100,000.00             0.00       100,000.00             0.00       100,000.00           NaN           NaN
NetIncomeIncludingNoncontrollingInterests            826,400,000.00   332,700,000.00 1,123,100,000.00   309,600,000.00   383,200,000.00           NaN           NaN
NetIncomeContinuousOperations                        826,400,000.00   332,700,000.00 1,123,100,000.00   309,600,000.00   383,200,000.00           NaN           NaN
TaxProvision                                        -456,800,000.00     3,500,000.00  -338,800,000.00    -2,700,000.00    11,800,000.00           NaN           NaN
PretaxIncome                                         369,600,000.00   336,200,000.00   784,300,000.00   306,900,000.00   395,000,000.00           NaN           NaN
SpecialIncomeCharges                                 -53,000,000.00    -7,700,000.00   -37,600,000.00   -13,100,000.00   -19,200,000.00           NaN           NaN
OtherSpecialCharges                                             NaN              NaN    24,300,000.00              NaN    28,900,000.00   -100,000.00 20,300,000.00
ImpairmentOfCapitalAssets                             19,300,000.00              NaN              NaN              NaN    28,900,000.00   -100,000.00           NaN
RestructuringAndMergernAcquisition                    33,700,000.00     7,700,000.00    13,300,000.00    13,100,000.00    -9,700,000.00           NaN           NaN
GainOnSaleOfSecurity                                   3,800,000.00   -17,700,000.00              NaN     1,500,000.00       200,000.00 -5,900,000.00           NaN
OperatingExpense                                     489,400,000.00   556,400,000.00    34,500,000.00   527,300,000.00   461,000,000.00           NaN           NaN
OtherOperatingExpenses                                80,200,000.00   145,600,000.00  -450,500,000.00   132,700,000.00    11,800,000.00           NaN           NaN
DepreciationAndAmortizationInIncomeStatement          42,000,000.00    42,400,000.00    44,400,000.00    44,800,000.00    43,000,000.00           NaN           NaN
Amortization                                          16,600,000.00    16,700,000.00              NaN    17,400,000.00              NaN 16,500,000.00           NaN
DepreciationIncomeStatement                           25,400,000.00    25,700,000.00    44,400,000.00    27,400,000.00    43,000,000.00           NaN           NaN
SellingGeneralAndAdministration                       62,100,000.00    62,700,000.00   119,700,000.00    64,300,000.00   119,500,000.00           NaN           NaN
SellingAndMarketingExpense                               600,000.00       500,000.00              NaN       700,000.00              NaN  3,500,000.00           NaN
GeneralAndAdministrativeExpense                       61,500,000.00    62,200,000.00   119,700,000.00    63,600,000.00   119,500,000.00           NaN           NaN
InsuranceAndClaims                                              NaN              NaN              NaN              NaN              NaN  4,600,000.00           NaN
TotalRevenue                                       1,014,200,000.00 1,005,800,000.00   989,600,000.00   951,700,000.00   972,600,000.00           NaN           NaN
OperatingRevenue                                   1,014,200,000.00 1,005,800,000.00   989,600,000.00   951,700,000.00   972,600,000.00           NaN           NaN

In [22]:
#Principali Azionisti
SH=Stock.get_major_holders()
SH

Breakdown                     Value
insidersPercentHeld            0.27
institutionsPercentHeld        0.23
institutionsFloatPercentHeld   0.31
institutionsCount            141.00

In [29]:
#Azionisti Istituzionali
Stock.get_institutional_holders()

Empty DataFrame
Columns: []
Index: []

In [ ]:
#Sustainability
Stock.get_sustainability()

In [26]:
#Raccomandazioni degli analisti
Stock.recommendations.sort_index(ascending=False)

  period  strongBuy  buy  hold  sell  strongSell
3   -3m       0       0     1     2        0
2   -2m       0       0     1     2        0
1   -1m       0       0     2     3        0
0    0m       0       0     0     0        0

In [27]:
#Calendario Principali eventi
Stock.calendar

{'Ex-Dividend Date': datetime.date(2024, 5, 20),
 'Earnings Date': [datetime.date(2024, 11, 7)],
 'Earnings High': 0.21,
 'Earnings Low': 0.21,
 'Earnings Average': 0.21,
 'Revenue High': 1001000000,
 'Revenue Low': 962000000,
 'Revenue Average': 979800000}

In [28]:
# show all earnings dates
Stock.earnings_dates

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2025-08-04 12:00:00+02:00       NaN           NaN          NaN
2025-05-05 12:00:00+02:00       NaN           NaN          NaN
2025-02-04 11:00:00+01:00       NaN           NaN          NaN
2024-11-07 11:00:00+01:00       NaN           NaN          NaN
2024-08-06 08:00:00+02:00      0.22          0.66         2.05
2024-08-05 12:00:00+02:00      0.21           NaN          NaN
2024-05-07 07:00:00+02:00      0.16          0.26         0.70
2024-05-06 12:00:00+02:00      0.15          0.26         0.73
2024-02-07 07:00:00+01:00      0.21          0.90         3.22
2023-11-08 08:00:00+01:00      0.15          0.24         0.60
2023-08-04 07:00:00+02:00      0.14          0.30         1.17
2023-05-13 01:00:00+02:00      0.13          0.19         0.44

In [30]:
#Options expirations ()
Stock.options

()

# Grafici e visualizzazione

In [31]:
StockHist = Stock.history(period='6mo')
StockHist.head()

                           Open  High  Low  Close   Volume   Dividends  Stock Splits
Date
2024-02-14 00:00:00+01:00  3.38  3.49 3.34  3.48   26692588    0.00         0.00
2024-02-15 00:00:00+01:00  3.49  3.56 3.40  3.40   27477458    0.00         0.00
2024-02-16 00:00:00+01:00  3.45  3.45 3.34  3.36   14759944    0.00         0.00
2024-02-19 00:00:00+01:00  3.36  3.39 3.31  3.32   16175878    0.00         0.00
2024-02-20 00:00:00+01:00  3.32  3.34 3.29  3.29   11320910    0.00         0.00

In [32]:
import plotly.graph_objects as go
fig = go.Figure(data=[go.Candlestick(x=StockHist.index.values,  open=StockHist['Open'],
high=StockHist['High'], low=StockHist['Low'], close=StockHist['Close'])])
fig.update_layout(autosize=False, width=1400, height=800)
fig.show()

In [33]:
import plotly.express as px
StockHist['DT']=StockHist.index.values
fig = px.line(StockHist, x="DT", y="Open", title='Stock Prices')
fig.show()

/usr/local/lib/python3.10/dist-packages/_plotly_utils/basevalidators.py:105: FutureWarning:

The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result

In [34]:
fig = go.Figure(data=go.Ohlc(x=StockHist['DT'], open=StockHist['Open'],high=StockHist['High'],low=StockHist['Low'], close=StockHist['Close']))
fig.update_layout(autosize=False, width=1400, height=900)
fig.show()

/usr/local/lib/python3.10/dist-packages/_plotly_utils/basevalidators.py:105: FutureWarning:

The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result